-- Convertir columnas escalares de integer a text
ALTER TABLE public.survey_responses
  ALTER COLUMN cuota_edad_cod TYPE text USING cuota_edad_cod::text,
  ALTER COLUMN p2_genero_cod TYPE text USING p2_genero_cod::text,
  ALTER COLUMN p3_profesion_cod TYPE text USING p3_profesion_cod::text,
  ALTER COLUMN p4_anos_profesion_cod TYPE text USING p4_anos_profesion_cod::text,
  ALTER COLUMN p5_proyecto_activo_cod TYPE text USING p5_proyecto_activo_cod::text,
  ALTER COLUMN p6_medio_movilizacion_cod TYPE text USING p6_medio_movilizacion_cod::text,
  ALTER COLUMN p7_usa_tubos_electricos_cod TYPE text USING p7_usa_tubos_electricos_cod::text,
  ALTER COLUMN p8_ultima_compra_cod TYPE text USING p8_ultima_compra_cod::text,
  ALTER COLUMN p9_frecuencia_uso_cod TYPE text USING p9_frecuencia_uso_cod::text,
  ALTER COLUMN p6_marca_preferida_cod TYPE text USING p6_marca_preferida_cod::text,
  ALTER COLUMN p10_recuerdo_indeco_cod TYPE text USING p10_recuerdo_indeco_cod::text,
  ALTER COLUMN a1_recuerda_cod TYPE text USING a1_recuerda_cod::text,
  ALTER COLUMN a1_marca_cod TYPE text USING a1_marca_cod::text,
  ALTER COLUMN a2_recuerda_cod TYPE text USING a2_recuerda_cod::text,
  ALTER COLUMN a2_marca_cod TYPE text USING a2_marca_cod::text,
  ALTER COLUMN a3_recuerda_cod TYPE text USING a3_recuerda_cod::text,
  ALTER COLUMN a3_marca_cod TYPE text USING a3_marca_cod::text;

-- Convertir columnas array de integer[] a text[]
ALTER TABLE public.survey_responses
  ALTER COLUMN p1_marcas_conocidas_espontanea_cod TYPE text[] USING p1_marcas_conocidas_espontanea_cod::text[],
  ALTER COLUMN p2_otras_marcas_conocidas_cod TYPE text[] USING p2_otras_marcas_conocidas_cod::text[],
  ALTER COLUMN p3_marcas_publicidad_vista_cod TYPE text[] USING p3_marcas_publicidad_vista_cod::text[],
  ALTER COLUMN p4_marcas_conocidas_lista_cod TYPE text[] USING p4_marcas_conocidas_lista_cod::text[],
  ALTER COLUMN p5_marcas_usadas_cod TYPE text[] USING p5_marcas_usadas_cod::text[],
  ALTER COLUMN p7_punto_venta_cod TYPE text[] USING p7_punto_venta_cod::text[],
  ALTER COLUMN p8_publicidad_marcas_cod TYPE text[] USING p8_publicidad_marcas_cod::text[],
  ALTER COLUMN p9_medios_koplast_cod TYPE text[] USING p9_medios_koplast_cod::text[],
  ALTER COLUMN p9_medios_tuboplast_cod TYPE text[] USING p9_medios_tuboplast_cod::text[],
  ALTER COLUMN p9_medios_eurotubo_cod TYPE text[] USING p9_medios_eurotubo_cod::text[],
  ALTER COLUMN p9_medios_pavco_cod TYPE text[] USING p9_medios_pavco_cod::text[],
  ALTER COLUMN p9_medios_nicoll_cod TYPE text[] USING p9_medios_nicoll_cod::text[],
  ALTER COLUMN p9_medios_matusita_cod TYPE text[] USING p9_medios_matusita_cod::text[],
  ALTER COLUMN p9_medios_plastisur_cod TYPE text[] USING p9_medios_plastisur_cod::text[],
  ALTER COLUMN p9_medios_indeco_cod TYPE text[] USING p9_medios_indeco_cod::text[],
  ALTER COLUMN a1_donde_vio_cod TYPE text[] USING a1_donde_vio_cod::text[],
  ALTER COLUMN a1_mensaje_cod TYPE text[] USING a1_mensaje_cod::text[],
  ALTER COLUMN a1_medio_sugerido_cod TYPE text[] USING a1_medio_sugerido_cod::text[],
  ALTER COLUMN a2_donde_vio_cod TYPE text[] USING a2_donde_vio_cod::text[],
  ALTER COLUMN a2_mensaje_cod TYPE text[] USING a2_mensaje_cod::text[],
  ALTER COLUMN a2_medio_sugerido_cod TYPE text[] USING a2_medio_sugerido_cod::text[],
  ALTER COLUMN a3_donde_vio_cod TYPE text[] USING a3_donde_vio_cod::text[],
  ALTER COLUMN a3_mensaje_cod TYPE text[] USING a3_mensaje_cod::text[],
  ALTER COLUMN a3_medio_sugerido_cod TYPE text[] USING a3_medio_sugerido_cod::text[];